# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

- name: NPM Publish
uses: JS-DevTools/npm-publish@v3.1.1
with:
  token: ${{ secrets.NPM_TOKEN }}  # Use the correct secret name
  registry: https://registry.npmjs.org/  # Explicitly set the registry
  package: ./  # Or specify the path to your package.json
  tag: latest  # Or a specific tag like 'next' or 'beta'
  access: public  # Or 'restricted' if needed
  provenance: true # Recommended for security
  strategy: 'upgrade' # Publish only if the version is an upgrade
  ignore-scripts: true # Recommended for security
  # dry-run: false  # Default is false, uncomment for testing
