# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release CI

on:
release:
  types: [created] # Trigger on release creation, not push

jobs:
publish-npm: # Combine build and release into one job
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3 # Use a more recent checkout action
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 10.x
        registry-url: "https://registry.npmjs.org"
        cache: 'npm' # Cache dependencies
    - name: Install dependencies
      run: npm ci  # Use npm ci for faster, more reliable installs
    - name: Build package
      run: npm run build:prod
    - name: Publish package
      run: npm publish --access public --provenance # Provenance is recommended
      working-directory: dist/lib # Use working-directory instead of cd
      if: success() # Publish only if previous steps succeed
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Use NPM_TOKEN, not NODE_AUTH_TOKEN
    - name: Create Release (if needed - usually done manually)
      if: success() && github.event_name == 'release'
      run: |
        VERSION=${GITHUB_REF/refs\/tags\//}
        gh release view "${VERSION}" # No need to create release here
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}