# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
release:
  types: [created]

jobs:
build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 10.x # Use a Node 10.x version
        cache: 'npm'
    - run: npm ci
    - run: npm run build  # If you have a build step in your project

publish-npm:
  needs: build
  runs-on: ubuntu-latest
  if: github.event_name == 'release' && github.event.action == 'created' # Only run on release creation
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 10.x  # Match Node version from build job
        registry-url: https://registry.npmjs.org/
        cache: 'npm'
    - run: npm ci
    - run: npm publish
      if: success()
      env:
        NPM_TOKEN: ${{secrets.npm_token}}
