name: NPM Package Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10'
          registry-url: 'https://registry.npmjs.org'
          scope: '@winnyboy5'

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run lib:build:prod

      - name: Publish to NPM
        run: |
          cd dist
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}